# Generated by Django 5.0.4 on 2024-07-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_score_initial_grade_alter_class_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingnote',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='gradingnote',
            name='grading_period',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradingNote',
        ),
    ]
