# Generated by Django 5.0.4 on 2024-07-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gradingnote_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grading_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gradingperiod'),
        ),
    ]
