# Generated by Django 5.0.4 on 2024-08-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_grading_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterly_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enrollment')),
                ('grading_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gradingperiod')),
            ],
            options={
                'unique_together': {('enrollment', 'grading_period')},
            },
        ),
    ]
