# Generated by Django 5.0.4 on 2024-08-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name_plural': 'School Years'},
        ),
    ]
