# Generated by Django 5.0.4 on 2024-10-28 12:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schoolyear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile.png', upload_to=core.models.user_directory_path),
        ),
    ]
