# Generated by Django 5.0.4 on 2024-11-01 02:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_administrator_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='core/images/default_profile.png', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='core/images/default_profile.png', upload_to=core.models.user_directory_path),
        ),
    ]
