# Generated by Django 5.0.4 on 2024-11-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='view_scores',
            field=models.BooleanField(default=True),
        ),
    ]
