# Generated by Django 5.0.4 on 2024-11-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enrollment_view_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='view_scores',
        ),
    ]
