# Generated by Django 5.0.4 on 2024-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_enrollment_view_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='scores_visible',
            field=models.BooleanField(default=True),
        ),
    ]
