# Generated by Django 5.0.4 on 2024-11-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_created_at_grade_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Middle_Initial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
