# Generated by Django 5.0.4 on 2024-11-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_teacher_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='Middle_Initial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Middle_Initial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
